# Generated by Django 5.0.5 on 2024-08-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residuos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('empresas', models.ManyToManyField(blank=True, related_name='residuos', to='empresa.empresa')),
            ],
        ),
    ]
